#!/bin/sh
# A simple script with a function...

add_numbers()
{
declare -i number1=$1
declare -i number2=$2
# declare statement declares a variable to be a number. By default variables are strings in shell
((sum=$number1 + $number2))
echo $sum
}

###
# Main body of scripts start here
###
echo "Start of Script"
add_numbers 1 3
echo "End of Script..."
